unbind C-b
set-option -g prefix C-t
bind-key C-t send-prefix
bind-key C-t last-window
set -sg escape-time 0
set -g base-index 1
set -g mouse on
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
if-shell "uname | grep -q Darwin" {
  bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
  bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
} {
  bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
  bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
}
bind-key p paste-buffer
bind r source-file ~/.tmux.conf
set -g status-right '#[bold] %H:%M:%S '
setw -g window-status-current-format ' #I:#[bold]#W '
setw -g window-status-format ' #I:#W '
setw -g status-left ''
set -g default-terminal "xterm-256color"
set -g status-style bg='#abd7f0',fg='#000000'
