#!/bin/sh
set -xe

CANDIDATES=$(xdotool search --onlyvisible --"$1" "$2")
CANDIDATES_LEN=$(echo "$CANDIDATES" | wc -w)
CURRENT=$(xdotool getactivewindow)

if ! { echo "$CANDIDATES" | grep -q "$CURRENT"; }; then
    IDX=$CANDIDATES_LEN
elif [ $(( CANDIDATES_LEN > 1 )) = 1 ]; then
    IDX=$(( CANDIDATES_LEN - 1 ))
else
    IDX=1
fi;

xdotool windowactivate "$(echo "$CANDIDATES" | sed -n "${IDX}p")"
