#!/bin/sh
set -x
set -e

CANDIDATES=$(xdotool search --onlyvisible --"$1" "$2")
CANDIDATES_LEN=$(echo "$CANDIDATES" | wc -w)
CURRENT=$(xdotool getactivewindow)

IS_NEW_TYPE="$(grep "$CURRENT" "$CANDIDATES" || true)"

if [ "$IS_NEW_TYPE" ]; then
    IDX=$CANDIDATES_LEN
elif [ $(( CANDIDATES_LEN > 1 )) = 1 ]; then
    IDX=$(( CANDIDATES_LEN - 1 ))
else
    IDX=1
fi;

xdotool windowactivate "$(echo "$CANDIDATES" | sed -n "${IDX}p")"
