#!/bin/sh
set -x

function contains() {
    local n=$#
    local value=${!n}
    for ((i=1;i < $#;i++)) {
        if [ "${!i}" == "${value}" ]; then
            echo 1
            return 0
        fi
    }
    echo 0
    return 1
}

CANDIDATES=( $(xdotool search --onlyvisible --"$1" "$2") )
CANDIDATES_LEN=${#CANDIDATES[@]}
CURRENT=$(xdotool getactivewindow)
IS_NEW_TYPE=!$(contains ${CANDIDATES[@]} $CURRENT)

IDX=0
if (( $IS_NEW_TYPE )); then
    IDX=$(expr $CANDIDATES_LEN - 1)
elif (( $CANDIDATES_LEN > 1 )); then
    IDX=$(($CANDIDATES_LEN - 2))
fi;

xdotool windowactivate ${CANDIDATES[$IDX]}
