(use-package exwm
  :config
  (require 'exwm)
  (require 'exwm-config)
  (exwm-config-default)
  (setq exwm-workspace-number 1)

  (require 'exwm-systemtray)
  (exwm-systemtray-enable)
  (customize-set-variable 'exwm-input-global-keys
                          `(([?\s-&] . (lambda (command)
                                         (interactive (list (read-shell-command "$ ")))
                                         (start-process-shell-command command nil command)))
                            ([?\s-g] . keyboard-quit)

                            ([?\s-h] . windmove-left)
                            ([?\s-j] . windmove-down)
                            ([?\s-k] . windmove-up)
                            ([?\s-l] . windmove-right)

                            ([?\s-H] . almacs/swap-left)
                            ([?\s-J] . almacs/swap-down)
                            ([?\s-K] . almacs/swap-up)
                            ([?\s-L] . almacs/swap-right)

                            ([?\s-w] . almacs/window-prefix-command)

                            ([?\s-t] . toggle-truncate-lines)

                            ([?\s-!] . (lambda ()
                                         (interactive)
                                         (shell-command "~/.screenlayout/internal.sh")))
                            ([?\s-@] . (lambda ()
                                         (interactive)
                                         (shell-command "~/.screenlayout/external.sh")))
                            ([?\s-#] . (lambda ()
                                         (interactive)
                                         (shell-command "~/.local/bin/kbd-us-intl.sh")))
                            ([?\s-I] . (lambda ()
                                         (interactive)
                                         (start-process-shell-command "jetbrains" nil "idea")))
                            ([?\s-C] . (lambda ()
                                         (interactive)
                                         (start-process-shell-command "chromium" nil "chromium")))

                            ([?\s-1] . eyebrowse-switch-to-window-config-1)
                            ([?\s-2] . eyebrowse-switch-to-window-config-2)
                            ([?\s-3] . eyebrowse-switch-to-window-config-3)
                            ([?\s-4] . eyebrowse-switch-to-window-config-4)

                            ([?\s-n] . almacs/next-buffer-within-prefix)
                            ([?\s-p] . almacs/prev-buffer-within-prefix)
                            ([?\s-N] . almacs/next-buffer)
                            ([?\s-P] . almacs/prev-buffer)
                            ([?\s-b] . helm-buffers-list)
                            ([?\s-B] . helm-browse-project)
                            ([?\s-r] . helm-resume)
                            ([?\s-u] . almacs/winner-undo)
                            ([?\s-M] . almacs/writeroom-enable)
                            ([?\s-m] . delete-other-windows)
                            ([?\s-F] . exwm-layout-set-fullscreen)
                            ([?\s-f] . exwm-layout-unset-fullscreen)
                            ([?\s-d] . delete-window)
                            ([?\s-D] . kill-this-buffer)
                            ([?\s-\ ] . almacs/prefix-command)
                            ([s-tab] . evil-buffer)
                            ([?\s-`] . exwm-input-send-next-key)
                            ([?\s-,] . almacs/switch-buffer-by-first-char)))

  (exwm-input-set-key (kbd "s-R") #'exwm-reset)
  (exwm-input-set-key (kbd "s-x") #'exwm-input-toggle-keyboard)
  (exwm-enable)

  (require 'exwm-randr)
  (exwm-randr-enable))
