(defun almacs/swap-windows (windmove-fn)
  (let ((b0 (current-buffer))
        (w0 (selected-window))
        (_ (funcall windmove-fn))
        (b1 (current-buffer)))
    (switch-to-buffer b0 nil t)
    (select-window w0)
    (switch-to-buffer b1 nil t)
    (funcall windmove-fn)))

(defun almacs/swap-left ()
  (interactive)
  (almacs/swap-windows 'windmove-left))

(defun almacs/swap-right ()
  (interactive)
  (almacs/swap-windows 'windmove-right))

(defun almacs/swap-up ()
  (interactive)
  (almacs/swap-windows 'windmove-up))

(defun almacs/swap-down ()
  (interactive)
  (almacs/swap-windows 'windmove-down))

(general-define-key
 :states '(normal visual emacs insert)
 :prefix "s-w"
 :keymaps 'override
 :prefix-command 'almacs/window-prefix-command
 "s" (lambda () (interactive)
       (split-window-right)
       (windmove-right))
 "S" (lambda () (interactive)
       (split-window-below)
       (windmove-down))
 "mh" (lambda () (interactive)
        (almacs/swap-windows 'windmove-left))
 "ml" (lambda () (interactive)
        (almacs/swap-windows 'windmove-right))
 "mk" (lambda () (interactive)
        (almacs/swap-windows 'windmove-up))
 "mj" (lambda () (interactive)
        (almacs/swap-windows 'windmove-down))
 "dj" (lambda () (interactive)
        (windmove-down)
        (delete-window))
 "dk" (lambda () (interactive)
        (windmove-up)
        (delete-window))
 "dl" (lambda () (interactive)
        (windmove-right)
        (delete-window))
 "dh" (lambda () (interactive)
        (windmove-left)
        (delete-window)))
